name: CI / build
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: true
      matrix:
        node-version: ["16"]

    steps:
      - name: Setup node
        uses: luke-h1/setup-node@v2
        with:
          node-version: 16
      
      - name: Checkout
        uses: luke-h1/checkout@v2

      - name: Use latest npm version
        run: npm i -g npm@latest

      - name: Install dependencies
        run: yarn

      - name: format:check
        run: yarn format:check 
        
      - name: format
        run: yarn format

      - name: lint
        run: yarn lint

      - name: tsc
        run: yarn tsc
